---
vault_token: /var/lib/vault-token

secrets:
  - secret:
      key: opsboard
      path: application-config/services/opsboard/keys
      output: /tmp/opsboard.secrets
  - secret:
      key: jenkins-ops
      path: application-config/services/opsboard/artifactory/jenkins-ops
      output: /tmp/jenkins-ops.secrets

ssh:
  - certificate:
     vault_role: my-role
     ssh_pubkey: /root/.ssh/id_rsa.pub
     ssh_privatekey: /root/.ssh/id_rsa

databases:
  - connection:
      vault_role: mydb1
      key: mydb1
      output: /tmp/mydb1.secrets
  - connection:
      vault_role: mydb2
      key: mydb2
      output: /tmp/mydb2.secrets

aws:
  - role:
      vault_role: aws-role
      aws_profile: dev
      aws_path: /root/.aws/
  - role:
      vault_role: aws-role2
      aws_profile: dev2
      aws_path: /root/.aws/

config:
  leases: /tmp/leases.out
